### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Shmew** [Shmew/Feliz.MaterialUI.MaterialTable#1]
Hey @cmeeren @zaid-ajaj if you have time I'd love a review/advice on the api and design of this library.

I've got almost everything implemented at this point. 

The main thing I'm unsure about is handling implementation of custom components like in this [example](https://shmew.github.io/Feliz.MaterialUI.MaterialTable/#/MaterialTable/Examples/ComponentOverriding) which is defined [here](https://github.com/Shmew/Feliz.MaterialUI.MaterialTable/blob/master/src/Bindings.fs#L155) does this look okay? Is there a better way I can provide this interface?

There is also the question of handling things like how they use refs for the refreshing section of this [example](https://material-table.com/#/docs/features/remote-data), I'm assuming I can figure it out by lifting the state up, but I haven't played with it yet.

Thanks!

**Comment by cmeeren** [comment]
Thanks for involving me! Unfortunately I don't have the time to look into this at the moment. I don't have the capacity to review a whole codebase, or even try to understand from your links what it is you want input on (which I'm a bit fuzzy on).

If you can extract just what you want input on and present it clearly and concisely in an issue, there's a greater chance I (and anyone else) will be able to review those specific things. :)

**Comment by Shmew** [comment]
Yeah I understand, I appreciate you taking the time to reply though! I'll do that once I've got everything more fully fleshed out and if I'm still having problems.
